#!/bin/bash
adb-tap 902 435
adb-tap 262 549
sendtext-android $(get-my-ip eth0)
adb-tap 769 831
adb-tap 293 721
sendtext-android 8888
adb-tap 758 859

add just 1
adb just by master 1
add just 2
add just 3
add just 4
add just by master2
